#!/bin/bash

# Imposta 100Hz su HDMI-0
xrandr --output HDMI-0 --mode 2560x1440 --rate 99.97

# Wallpaper
~/.fehbg &

# Disattiva DPMS e blanking
xset s off
xset -dpms
xset s noblank

# Avvia fish e i3
exec fish -l -c i3
