#!/usr/bin/env fish

sudo mkdir -p /etc/systemd/system/getty@tty1.service.d

printf "[Service]\nExecStart=\nExecStart=-/usr/bin/agetty --autologin mattia --noclear %%I \$TERM\n" \
| sudo tee /etc/systemd/system/getty@tty1.service.d/override.conf > /dev/null
