#!/bin/bash
set -e

if [[ $EUID -ne 0 ]]; then
    echo "Per favore esegui questo script con sudo o come root."
    exit 1
fi

PACMAN_PKGS=(
    base
    android-file-transfer
    libmtp
    fuse2
    base-devel
    calc
    chezmoi
    cmus
    dhcpcd
    efibootmgr
    fastfetch
    feh
    figlet
    firefox
    firefox-ublock-origin
    fish
    freetype2
    git
    github-cli
    gnupg
    gst-plugin-pipewire
    htop
    kitty
    libx11
    libxft
    libxinerama
    linux
    linux-firmware
    lsd
    maim
    mc
    micro
    mesa
    mpv
    noto-fonts-emoji
    openssh
    pass
    pipewire
    pipewire-alsa
    pipewire-jack
    pipewire-pulse
    qbittorrent
    ttf-nerd-fonts-symbols-mono
    ufw
    unzip
    vulkan-icd-loader
    wget
    wireplumber
    xclip
    xdotool
    xorg-server
    xorg-setxkbmap
    xorg-xinit
    xorg-xmodmap
    xorg-xrandr
    xorg-xset
    zram-generator
)

pacman -Syu --needed "${PACMAN_PKGS[@]}"
