#!/bin/bash

choice="$(printf "shutdown\nreboot\nkill" | dmenu -i -c -l 4 -p "Power menu")"

confirm() {
    printf "no\nyes" | dmenu -i -c -l 2 -p "Are you sure?"
}

case "$choice" in
    shutdown)
        if [ "$(confirm)" = "yes" ]; then
            sudo shutdown now
        fi
        ;;
    reboot)
        if [ "$(confirm)" = "yes" ]; then
            sudo reboot
        fi
        ;;
    kill)
        ps -u "$USER" -o pid,comm,%cpu,%mem | dmenu -i -c -l 10 -p "Kill:" | awk '{print $1}' | xargs -r kill
        ;;
    *)
        exit 1
        ;;
esac
