#!/bin/bash

case "$(printf "kill\nreboot\nshutdown" | dmenu -i -c -l 4)" in
	kill) ps -u $USER -o pid,comm,%cpu,%mem | dmenu -i -c -l 10 -p Kill: | awk '{print $1}' | xargs -r kill ;;
	reboot) sudo reboot -i ;;
	shutdown) sudo shutdown now ;;
	*) exit 1 ;;
esac
